### ISSUE TITLE
Some information about the algorithm?

### ISSUE THREAD

**Issue by logic1988** [tatsy/lime#2]
Thanks for your great work!  This project had not been updated for a long time. Will it be updated later?

The example pencil_drawing was too `complicated`, can you provided some information about it's algorithm?

@tatsy

**Comment by tatsy** [comment]
Hi @logic1988, 

Thanks for your interest to my project. Actually, this project has not been updated for a while. While I would like to add a lot of new functions to this library, I do not have enough time to do it. So, please forgive me.

Anyway, for ```pencil_drawing``` example, it is almost an implementation of the following paper.

> A Stylized Approach for Pencil Drawing from Photographs
> http://onlinelibrary.wiley.com/doi/10.1111/j.1467-8659.2012.03143.x/full

Therefore, looking throughout this paper would help you to understand the example.
If you have some questions for specific parts of my code, I am always open to answer your question.

**Comment by logic1988** [comment]
Thank you! Can you give a todo list? Maybe we can help you.

**Comment by tatsy** [comment]
Hi @logic1988,

Thank you for offering me a help.

What I currently want to do on this project is to add a fast bilateral filtering and some soft segmentation algorithms. So, the update would not be just an update of the current code. I think it would be too much for asking a help for someone...

For the current code. I think they would be work well. If you have any trouble for the current code. It would be a great help if you revise the codes, and also I can help you to revise them.

If you have any specific trouble for this project. I will close this issue.

**Comment by logic1988** [comment]
If I have any questions, I will ask you. Thanks again.

**Comment by tatsy** [comment]
Hi @logic1988,

It's my pleasure. Thanks again for your interest and kindness.
